name: Execute Workflow on SLURM
on:
  push:
    tags:
    - '*'
jobs:
  execute:
    name: Execute on SLURM
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/slurm.key
          chmod 600 ~/.ssh/slurm.key
          cat >>~/.ssh/config <<END
          Host slurm
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/slurm.key
            StrictHostKeyChecking no
            ForwardAgent yes
            PasswordAuthentication no
          END
        env:
          SSH_USER: ${{ secrets.SLURM_USER }}
          SSH_KEY: ${{ secrets.SLURM_SSH_KEY }}
          SSH_HOST: ${{ secrets.SLURM_LOGIN_HOST }}
      - name: Configure Target Directory
        run: echo "TARGET_DIR=${{ secrets.SLURM_TMP }}/$(echo ${{ github.ref_name }} | iconv -t ascii//TRANSLIT | sed -E -e 's/[^[:alnum:]]+/-/g' -e 's/^-+|-+$//g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Download Source Code
        run: ssh slurm git clone --depth 1 --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git $TARGET_DIR
      - name: Install Packages
        run: ssh slurm -tt "module load python-data; pip install -r $TARGET_DIR/requirements.txt --user"
        name: Transfer Env
        run: |
          ssh slurm echo S3_KEY=$S3_KEY >> $TARGET_DIR/.env
          ssh slurm echo S3_PASS=$S3_PASS >> $TARGET_DIR/.env
          ssh slurm cat $TARGET_DIR/.env
      - name: Execute
        run: ssh slurm -tt sbatch -D $TARGET_DIR --wait $TARGET_DIR/slurm.sh
      - name: Print Results
        if: success() || failure()
        run: ssh slurm cat $TARGET_DIR/*.out
      - name: Check Data Output
        run: ls ./tmp/out
      - name: Cleanup
        if: success() || failure()
        run: ssh slurm rm -rf $TARGET_DIR