name: Execute Workflow on SLURM
on:
  push:
    tags:
    - '*'
jobs:
  execute:
    name: Execute on SLURM
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/slurm.key
          chmod 600 ~/.ssh/slurm.key
          cat >>~/.ssh/config <<END
          Host slurm
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/slurm.key
            StrictHostKeyChecking no
            ForwardAgent yes
            PasswordAuthentication no
          END
        env:
          SSH_USER: ${{ secrets.SLURM_USER }}
          SSH_KEY: ${{ secrets.SLURM_SSH_KEY }}
          SSH_HOST: ${{ secrets.SLURM_LOGIN_HOST }}
      - uses: actions/checkout@v3
      - name: Execute
        run: (export -p; cat ./.github/workflows/slurm-execute.sh) | ssh slurm 'bash -s'
        env:
          TAG: ${{ github.ref_name }}
          TARGET_TMP_DIR: ${{ secrets.SLURM_TMP }}
          REPO: ${{ github.repository }}