name: Execute Workflow on SLURM
on:
  push:
    tags:
    - '*'
jobs:
  execute:
    name: Execute on SLURM
    runs-on: ubuntu-latest
    steps:  
      - name: Execute
        uses: franjurinec/rahti-executor-action@0.3
        with:
          mahti-username: ${{ secrets.SLURM_USER }}
          mahti-password: ${{ secrets.SLURM_PASS }}
          mahti-base-dir: "/scratch/project_2005083/fran-testing"
          data-source-env: ${{ secrets.SOURCE_ENV }}
          invenio-key: ${{ secrets.INVENIO_API_KEY }}